import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

const interSans = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Forge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.className} antialiased`}>{children}</body>
    </html>
  );
}
